AWSTemplateFormatVersion: 2010-09-09

Description: Resource creation

Resources:
  MyAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-052c08d70def0ac62
      InstanceType: t2.micro
      KeyName: tw
      UserData: 
        Fn::Base64: !Sub |
          #!bin/bash
          echo y | dnf install httpd wget php php-mysqlnd php-gd php-xml php-mbstring php-json
          chkconfig httpd on
          cd /home/ec2-user
          wget https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz
          wget https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz.sig
          gpg --verify mediawiki-1.34.2.tar.gz.sig mediawiki-1.34.2.tar.gz
          cd /var/www
          tar -zxf /home/username/mediawiki-1.34.2.tar.gz
          ln -s mediawiki-1.34.2/ mediawiki

         # service httpd restart
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
  
  # an elastic IP for our app instance
  MyAppEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyAppInstance

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges on port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 192.168.1.1/32
